### PR TITLE
Fix "Non-ASCII character '\xe2' in file"

### PR DESCRIPTION
**Pull request by nathanwebsterdotme**
Fixes https://github.com/jaraco/zipp/issues/50

### CODE REVIEW

**Comment by nathanwebsterdotme** [comment]
@jaraco

**Comment by jaraco** [comment]
The latest master doesn’t support Python 2, so this patch probably won’t help

**Comment by bhundven** [comment]
I think the PR needs to change from merging into jaraco:master to merging into maint/1.x, then maybe tag it v1.2.1

**Comment by jaraco** [comment]
You're right that targeting the `maint/1.x` is the right thing to do for bugfixes that need to affect Python 2 compatible releases. Unfortunately, this patch won't help as the reported issue was actually downloading zipp 3. Yes, this patch would address that specific error, but it wouldn't address subsequent incompatibilities. Thanks for preparing it, though.

**Pull request closed without merging**
