### PR TITLE
Restore support for special filenames

### PR DESCRIPTION
**Pull request by jaraco**
Closes python/cpython#123270

### CODE REVIEW

**Comment by obfusk** [comment]
> That's interesting. The new `backslash_is_not_separator` test is failing on Windows:

Oh yeah, `ZipInfo.__init__()` calls `_sanitize_filename()`, which will replace `os.sep` with `/`.

**Comment by jaraco** [comment]
> Oh yeah, `ZipInfo.__init__()` calls `_sanitize_filename()`, which will replace `os.sep` with `/`.

I confirmed the same. I wonder if it's possible to construct a ZipFile with backslashes on Windows.

**Comment by jaraco** [comment]
> > Oh yeah, `ZipInfo.__init__()` calls `_sanitize_filename()`, which will replace `os.sep` with `/`.
> 
> I confirmed the same. I wonder if it's possible to construct a ZipFile with backslashes on Windows.

Looks like I can maybe overwrite the `.filename` after construction.

**Comment by jaraco** [comment]
@obfusk, any comments before I merge and cut a release?

**Pull request merged**
